### ISSUE TITLE
aglio includes don't work

### ISSUE THREAD

**Issue by samartioli** [nnnnathann/gulp-aglio#6]
Because this is run from gulp, trying to include paths in the .md files is always looking for them in the root directory. 

includePath	string	process.cwd()	Base directory for relative includes.

**Comment by samartioli** [comment]
https://github.com/danielgtaylor/aglio#including-files

**Comment by ArtemGordinsky** [comment]
Bummer. Are there any workarounds?

**Comment by nnnnathann** [comment]
Would love to get this working, not super familiar with the includes and how it would work with Gulp, do you guys have ideas on how you would like it to work?

**Comment by ArtemGordinsky** [comment]
Basically, aglio's cli utility inlines all included files (e.g. ```<!-- include(filename.md) -->```) when it renders the file. I expected the same behaviour when running it from your plugin, but instead got an error saying that referenced file does not exist. As far as I can see, the reason is that relative paths are not working here for some reason, and aglio tries to resolve all paths as if they were absolute and looks for the files in the root directory.

**Comment by nnnnathann** [comment]
Should be fixed in v0.0.10, thanks to you both.

Looks like the problem had to do with aglio defaulting to `process.cwd()`

I changed the plugin around to use the dirname of the current input file by default.

**Comment by ArtemGordinsky** [comment]
Great, thanks!
